### ISSUE TITLE
Init message broken

### ISSUE THREAD

**Issue by monoclex** [Yonom/CupCake#69]
In the latest version of cupcake I'm running, I get this:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Value at index:5 is not System.String. It's a System.Int32. Value is: 1
   at PlayerIOClient.Internal.identifier957.get[T](UInt32 index)
   at CupCake.Messages.Receive.InitReceiveEvent..ctor(Message message)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at CupCake.Messages.RegisteredMessage`1.Invoke(Message message)
   at CupCake.Messages.MessageService.HandleMessage(Message e)
   at Nito.Async.ActionDispatcher.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Positiong 5 is the player ID, not the username. e.GetString( 13 ); is what you need

**Comment by monoclex** [comment]
This'd be fixed if my pull request was pulled
